name: Plugin
version: 1.0
main: test.Plugin
api-version: '1.19'
load: STARTUP
commands:
  test_command:
  test_command0:
    aliases: []
    description: '21343134'
    usage: /<command> 21343134
    permission: permission.test
    permission-message: No perm